version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  build:
    executor:
      name: android/android-machine
      tag: 2021.10.1
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - run:
          name: Check, test and build the app.
          command: |
            echo "keyPassword=$RELEASE_KEY_PASSWORD" >> signing.properties
            # convert to env var
            # - base64 ./release.keystore > ./release.keystore.base64
            # - Copy content of ./release.keystore.base64 to env var
            echo $RELEASE_KEYSTORE_BASE64 | base64 --decode > release.keystore
            echo $GOOGLE_SERVICES_JSON > app/google-services.json
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            ./gradlew check assembleRelease bundleRelease
            # remove file to not include it as artifact
            rm app/build/outputs/apk/release/output-metadata.json
      - persist_to_workspace:
          root: app/build/outputs/
          paths:
            - apk/release/*.apk
            - bundle/release/*
            - mapping/release/mapping.txt
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports/lint-results.html
      - store_artifacts:
          path: app/build/outputs/apk/release
      - store_artifacts:
          path: app/build/outputs/bundle/release
      - store_artifacts:
          path: app/build/outputs/mapping/release/mapping.txt

  publish-google-play:
    executor:
      name: android/android-machine
      tag: 2021.10.1
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - run:
          name: Check, test, build and publish the app to firebase.
          command: |
            echo "keyPassword=$RELEASE_KEY_PASSWORD" >> signing.properties
            # convert to env var
            # - base64 ./release.keystore > ./release.keystore.base64
            # - Copy content of ./release.keystore.base64 to env var
            echo $RELEASE_KEYSTORE_BASE64 | base64 --decode > release.keystore
            echo $GOOGLE_SERVICES_JSON > app/google-services.json
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            ./gradlew check assembleRelease bundleRelease publish
            # remove file to not include it as artifact
            rm app/build/outputs/apk/release/output-metadata.json
      - persist_to_workspace:
          root: app/build/outputs/
          paths:
            - apk/release/*.apk
            - bundle/release/*
            - mapping/release/mapping.txt
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/release
      - store_artifacts:
          path: app/build/outputs/bundle/release
      - store_artifacts:
          path: app/build/outputs/mapping/release/mapping.txt

  publish-github-release:
    docker:
      - image: circleci/golang:1.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_PERSONAL_ACCESS_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/apk/release/*.apk
            ghr -t ${GITHUB_PERSONAL_ACCESS_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/bundle/release/
            ghr -t ${GITHUB_PERSONAL_ACCESS_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/mapping/release/mapping.txt

workflows:
  version: 2
  build-n-publish:
    jobs:
      - build
      - publish-google-play:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-github-release:
          requires:
            - publish-google-play
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
